name: projeto3
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  syncfusion_flutter_gauges: ^22.1.37
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/icon_mileage.png
    - assets/img/adaptive-icon.png

# https://pub.dev/packages/flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: false
  windows:
    generate: true
    image_path: assets/img/icon_mileage.png
    icon_size: 48
  remove_alpha_ios: true
  image_path: assets/img/adaptive-icon.png
  adaptive_icon_background: '#FF450D'
  adaptive_icon_foreground: assets/img/adaptive-icon.png
